//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ServiceModel;
using System.Xml.Serialization;

namespace Sap.PP0370;

/// <summary>
/// SAP I/F XmlSerializerFormat 필수 
/// XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)
/// </summary>

[ServiceContract]
public interface ISapPP0370
{
    [OperationContract]
    [XmlSerializerFormatAttribute()]
    PP0370_Response SI_GRP_PP0370_SO(PP0370_Request request);
}



